### ISSUE TITLE
Documentation needs work

### ISSUE THREAD

**Issue by dsoloha** [dsoloha/native-macos#10]
# To-do

### `EDITOR.md`
- [ ] Organize items `EDITOR.md` by which part of the VSCode editor they belong to
- [ ] Add a short description to each property

### `SCOPES.md`
- [ ] Add the rest of the scopes
- [ ] Add a short description for each scope
- [ ] Add more "hidden" properties

### `COLORS.md`
- [ ] Add a swatch image to each color
- [ ] Standardize color pallette
- [x] Combine colors that are close enough visually
